### ISSUE TITLE
Skipping all Annotations

### ISSUE THREAD

**Issue by janbernhardt** [mikepenz/action-junit-report#1020]
I want to publish the JUnit formatted CVE scan results with this plugin. But I do not want to create annotations on my summary, I only want to see the errors on my check. As far as I understand setting the annotations_limit to zero would also skip my errors on the check details.

**Comment by mikepenz** [comment]
Good day. 

Setting `annotations_limit` to zero would actually result in no annotations being collected at all, and I suppose you still want them to show up in the summary. 

If I understand you want the summary only, but no annotations whatsoever? (Basically skipping this: https://github.com/mikepenz/action-junit-report/blob/main/src/main.ts#L110-L119 ?)

**Comment by mikepenz** [comment]
Please feel free to try out this branch to see if it matches what you were looking for: https://github.com/mikepenz/action-junit-report/pull/1022

**Comment by janbernhardt** [comment]
Wow that was a super fast response. Very impressive!! I will test it and let you know.

**Comment by janbernhardt** [comment]
The summary_only skips the annotations as desired, but unfortunately it also skips the check report.

I would like to still see the check report but not the annotations.

Maybe a better option could be `annotate_error` which is `true` by default, but can be set to `false` to mute the error annotations.

**Comment by mikepenz** [comment]
Thank you for testing it. 

So you would like to have:
- checks
- summary
- but not annotations
(if I understand correctly?)

**Comment by janbernhardt** [comment]
yes, I want to show all the details, but not as an annotation error on top level of my workflow. I'm using it to show CVE issues from used dependencies, so there could be a lot of them. I want the users to be able to see the full list but I don't want to highlight them all in the annotations.

**Comment by mikepenz** [comment]
Thank you for your feedback. Based on this I decided to go a different route. This should be what you are looking for: 
- https://github.com/mikepenz/action-junit-report/pull/1024

New setting to disable the annotations for checks (does not affect. if `annotate_only` is used)

**Comment by janbernhardt** [comment]
Annotations are gone as desired. But my Check report is empty now as well. This is not desired, as I would still like to see the failed tests on the check report.

Now:
![image](https://github.com/mikepenz/action-junit-report/assets/1104935/ac0735a3-0e97-410f-beb1-a4b5b8055036)

Previous and desired output on the check would be:
![image](https://github.com/mikepenz/action-junit-report/assets/1104935/af8b09f0-91b4-40a1-adfe-4863c9fe1d3a)

**Comment by janbernhardt** [comment]
Maybe it is not possible to skip the annotations on the check summary...
I just want to avoid the Annotations on the build summary

![image](https://github.com/mikepenz/action-junit-report/assets/1104935/89c9f9d5-55ae-49eb-ac61-03dc75c91106)

**Comment by mikepenz** [comment]
@janbernhardt unfortunately this is not possible as far as I am aware. 

The annotations section is filled by GitHub automatically with the annotations created.

**Comment by mikepenz** [comment]
The summary could serve as alternative, however it's also not exactly the same

**Comment by janbernhardt** [comment]
Yes, you are right. Good point.

**Comment by janbernhardt** [comment]
So from my point of view, you can merge this change back into master :-)

**Comment by janbernhardt** [comment]
Summary details look like this
![image](https://github.com/mikepenz/action-junit-report/assets/1104935/b1c14168-a1e8-4419-9c7a-84a507667f98)
