### ISSUE TITLE
missing mypy detail when annotate_only=true

### ISSUE THREAD

**Issue by Alex-ley-scrub** [mikepenz/action-junit-report#1049]
as briefly mentioned in: https://github.com/mikepenz/action-junit-report/issues/699#issuecomment-1983734072

basically when you have `annotate_only=false` (the default) you see something like this (similar to the repo README images):

and when you click "Raw Output" button you see the mypy error:

<img width="1198" alt="image" src="https://github.com/mikepenz/action-junit-report/assets/94057608/ac6e6dce-f047-4b58-9140-7f66042d58df">

but with `annotate_only=true` you don't have the "Raw Output" button and therefore can't see the erorr

<img width="613" alt="image" src="https://github.com/mikepenz/action-junit-report/assets/94057608/34552688-12b1-4f9f-a417-1d87c1e0cb08">

**Comment by mikepenz** [comment]
Upon a closer look, this is unfortunately a limitation from GitHub. There is a difference if a check is created, or if a normal annotation is built. 

For the `annotate_only` a annotation property can be provided, and these don't allow for any additional information. 
- https://github.com/mikepenz/action-junit-report/blob/main/src/annotator.ts#L39-L53
- https://github.com/actions/toolkit/blob/ef77c9d60bdb03700d7758b0d04b88446e72a896/packages/core/src/core.ts#L40

While check do allow an additional raw_details to bo be provided
- https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#list-check-run-annotations

**Comment by mikepenz** [comment]
The only "alternative" I could think of would be to add the stacktrace as part of the message for the annotation, however not everyone may like that as it is quite verbose and there is no collapsing for it

**Comment by mikepenz** [comment]
@Alex-ley-scrub related the summary output: https://github.com/mikepenz/action-junit-report/pull/1050 
It would be great if you could try it out if it matches what you needed.

**Comment by mikepenz** [comment]
Closing as we won't be able to have the same output for annotation_only.
