### ISSUE TITLE
failed tests consist of the test name 2 times

### ISSUE THREAD

**Issue by igagis** [mikepenz/action-junit-report#105]
Instead of `<suite-name>.<test-name>` the UI shows `<test-name>.<test-name>`.
See test run here:
https://github.com/cppfw/tst/runs/2314883648

The test report is:
````xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name='factorial' tests='22' disabled='10' failures='4' errors='2'>
		<testcase name='disabled_fixture_test' status='disabled'/>
		<testcase name='disabled_param_fixture_test[0]' status='disabled'/>
		<testcase name='disabled_param_fixture_test[1]' status='disabled'/>
		<testcase name='disabled_param_fixture_test[2]' status='disabled'/>
		<testcase name='disabled_param_fixture_test[3]' status='disabled'/>
		<testcase name='disabled_param_test[0]' status='disabled'/>
		<testcase name='disabled_param_test[1]' status='disabled'/>
		<testcase name='disabled_param_test[2]' status='disabled'/>
		<testcase name='disabled_param_test[3]' status='disabled'/>
		<testcase name='disabled_test' status='disabled'/>
		<testcase name='factorial_of_value_from_fixture' status='failed'>
			<failure message='/home/ivan/prj/tst/tests/failed/main.cpp:58: error: check_eq(3628800, 3628801)'/>
		</testcase>
		<testcase name='factorial_of_value_from_fixture[0]' status='failed'>
			<failure message='/home/ivan/prj/tst/tests/failed/main.cpp:97: error: condition was false'/>
		</testcase>
		<testcase name='factorial_of_value_from_fixture[1]' status='passed'/>
		<testcase name='factorial_of_value_from_fixture[2]' status='passed'/>
		<testcase name='factorial_of_value_from_fixture[3]' status='passed'/>
		<testcase name='positive_arguments_must_produce_expected_result' status='errored'>
			<error message='uncaught std::exception: thrown by test'/>
		</testcase>
		<testcase name='positive_arguments_must_produce_expected_result[0]' status='passed'/>
		<testcase name='positive_arguments_must_produce_expected_result[1]' status='passed'/>
		<testcase name='positive_arguments_must_produce_expected_result[2]' status='failed'>
			<failure message='/home/ivan/prj/tst/tests/failed/main.cpp:73: error: condition was false'/>
		</testcase>
		<testcase name='positive_arguments_must_produce_expected_result[3]' status='passed'/>
		<testcase name='test_which_fails_check_eq_with_custom_message' status='failed'>
			<failure message='/home/ivan/prj/tst/tests/failed/main.cpp:49: error: check_eq(6, 7): hello world!'/>
		</testcase>
		<testcase name='test_which_throws_unknown_exception' status='errored'>
			<error message='uncaught unknown exception'/>
		</testcase>
	</testsuite>
</testsuites>
````

**Comment by mikepenz** [comment]
Thank you for the report. There will be a small improvement to the name discovery: https://github.com/mikepenz/action-junit-report/pull/125

By default the suite is not included in the name, for that please specify the `suite_regex`

**Comment by igagis** [comment]
I have added `suite_regex: '*'` and now the reported test names look like:

` positive_arguments_must_produce_expected_result.factorial/positive_arguments_must_produce_expected_result`

See https://github.com/cppfw/tst/runs/2362134146?check_suite_focus=true

So, the test name `positive_arguments_must_produce_expected_result` still appears two times.

I'd expect it to look like this:

`factorial.positive_arguments_must_produce_expected_result`

**Comment by mikepenz** [comment]
@igagis this happens here: https://github.com/mikepenz/action-junit-report/blob/main/src/testParser.ts#L191-L194

**Comment by mikepenz** [comment]
What could be done is to add another condition to compare the retrieved filename and testname and if they are equal to not retain both

**Comment by igagis** [comment]
Ok, so what is the intention of the code?

Is it so that in case we don't have suite (`suiteName` is empty), then instead of the suite name we use file name?

Then, why does in my case the `pos.fileName` have the same value as `testcase._attributes.name`?

Should the code be like this?
```typescript
const title = suiteName
          ? `${suiteName}.${testcase._attributes.name}`
          : `${pos.fileName}.${testcase._attributes.name}`
```

**Comment by igagis** [comment]
It is almost perfect now: https://github.com/cppfw/tst/runs/2400946865?check_suite_focus=true

Although, a small thing still can be improved, I have already commented on that in the PR, but I'll repeat here:

I think that dot is a bad delimiter for file and suite names, because file name can have dots itself. It is better to use slash to delimit file and suite names and dot to delimit suite and test names
