### ISSUE TITLE
the UI does not show number of disabled tests

### ISSUE THREAD

**Issue by igagis** [mikepenz/action-junit-report#106]
See test run here:
https://github.com/cppfw/tst/runs/2314883648

The UI shows `42 tests run, 0 skipped, 6 failed.`, but does not show number of disabled tests.

The test report file is same as in #105

**Comment by mikepenz** [comment]
This is currently not supported. Happy to take a PR to add support for the disabled count.

**Comment by igagis** [comment]
I'd be happy to help, but I'm total 0 at  `typescript` :(

**Comment by mikepenz** [comment]
Will include this as part of the skipped count.

**Comment by mikepenz** [comment]
thanks for the report
