### ISSUE TITLE
for which job the report is shown?

### ISSUE THREAD

**Issue by igagis** [mikepenz/action-junit-report#107]
Please see the workflow run:
https://github.com/cppfw/tst/actions/runs/737008009

it has several jobs configured. The tests are run in several of those jobs, each generates a report file.
So, why isn't report published separately for each job?

**Comment by mikepenz** [comment]
If you want to have it shown with different names you will be required to configure the `check_name`, otherwise the default name is used

**Comment by igagis** [comment]
thanks, that worked!
