### ISSUE TITLE
publishing test report failed, but overall workflow succeeded

### ISSUE THREAD

**Issue by igagis** [mikepenz/action-junit-report#111]
Have a look the workflow run https://github.com/cppfw/tst/actions/runs/743133656

One of the test reports has failed, but overall workflow status is succeeded. Is it possible to fail the workflow run as well in case there are problems with any of the test reports?

**Comment by mikepenz** [comment]
Hey. 

Have you had a look at the `fail_on_failure` configuration?
https://github.com/mikepenz/action-junit-report#inputs

**Comment by igagis** [comment]
Thanks, I overlooked that.

What are the possible values for this? `true`/`false`?
Documentation does not mention that.

**Comment by mikepenz** [comment]
@igagis exactly, possible values is either true or false. 

The default is set to `false`
https://github.com/mikepenz/action-junit-report/blob/main/action.yml#L28-L31

**Comment by igagis** [comment]
Thank you!
