### ISSUE TITLE
Annotations not being produced

### ISSUE THREAD

**Issue by mendezj-eikontx** [mikepenz/action-junit-report#1121]
For over a month now I've been using this action to parse junit results and produce annotations. Starting yesterday (20 June 2024), this action stopped producing annotations. It still shows the number of tests, failures, and errors, but it says "no test annotations available". I have `include_passed: true` in my workflow, so I should see annotations for all of our tests (879 total).

I re-ran the tests in a previous run that had annotations originally, but now I get the same "no test annotations available" message after re-running it.

**Comment by mikepenz** [comment]
@mendezj-eikontx thank you very much for the report. 

I have reverted the last v4 release to v4.2.2 and added a warning to v4.3.0 while I investigate. I suppose it might be a side effect of the v4.3.0 release including some performance optimisations to speed the processing up. 

If you use `@v4` things should be fine again. I really apologize for the problem.

**Comment by mikepenz** [comment]
Released v4.3.1 to fix the problem.
