### ISSUE TITLE
Failed to create checks using the provided token.

### ISSUE THREAD

**Issue by saisanthoshkonduri** [mikepenz/action-junit-report#1126]
I have passed the correct GITHUB_TOKEN. The project is Maven. Is it compatible with Maven? It is causing the issue below. Could you please help me here?

This is the codeblock,

        name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.qualitygate.wait=true -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml sonar:sonar -Dsonar.projectKey=XYZ

        name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success() || failure()
        with:
          report_paths: 'target/site/jacoco/jacoco.xml'

![sonar](https://github.com/mikepenz/action-junit-report/assets/171614938/47498784-5f8c-471e-af46-61e287eb866c)

**Comment by mikepenz** [comment]
Please verify the token has the correct permission: https://github.com/mikepenz/action-junit-report?tab=readme-ov-file#pr-run-permissions

**Comment by saisanthoshkonduri** [comment]
Yes, that's the org-level token, and it has all the required permissions.

**Comment by mikepenz** [comment]
So your build does include?
```yml
permissions:
  checks: write
``` 
  
The error from the screenshot indicates that the provided token does not have the permission to crate those annotations, indicating the token needs higher priviledges

**Comment by saisanthoshkonduri** [comment]
No, where can I include it in the Maven project?

**Comment by mikepenz** [comment]
Please check the README: https://github.com/mikepenz/action-junit-report?tab=readme-ov-file#pr-run-permissions

It links to GitHub's documentation for more information on the permissions of the tokens. and why this is necessary.
