### ISSUE TITLE
Multiple XML file locations

### ISSUE THREAD

**Issue by kajoshi0117** [mikepenz/action-junit-report#1140]
Hello all 👋 

I have a JS project that uses a modular structure, with `libs/` and `apps/` directories with their own test suites, thus resulting in multiple XML file locations in various subdirectories of the `libs/some_lib/some_lib_subdirectory/junit.xml` file locations. 

Is this action capable of handling multiple xml file locations? It seems like it is based on the documentation but im struggling to get it to work. 

I've been messing with the `report_paths` parameter to try and get it to work, but its not finding the XML files. I attempted to try and use a glob pattern, such as `'libs/**/junit.xml,apps/**/junit.xml'` but its not working. 

Then I tried to create a separate step in my GitHub Actions to find all locations of the `junit.xml` file, set that as a step output, and plug that output into the `report_paths` parameter, and still was not working. I've been able to successfully get all the paths, it's just that the action is not reporting/finding . 

Any suggested tips or practices on how to handle this type of situation? Thanks! 🙂

**Comment by mikepenz** [comment]
Good day @kajoshi0117 

Yes the action supports multiple `report_paths`, however the syntax to pass multiple values in YAML is different. It has all entries in a new line. 

An example:
https://github.com/mikepenz/action-junit-report/blob/main/.github/workflows/build.yml#L71-L88


Alternative, as this is a glob pattern, why don't use use: `*/**/junit.xml`?

**Comment by kajoshi0117** [comment]
I see now based on the example and the easier glob helped out, (im new to using them) thanks for the reply! I was able to get it successfully working and have it accurately reporting all test suites now! 👍  
I'll tinker around with the action some more and explore more of the capabilities 😄
