### ISSUE TITLE
Question on annotations when the action is applied in a resuable workflow

### ISSUE THREAD

**Issue by watermarkhu** [mikepenz/action-junit-report#1153]
Hi!

I've got a question on the annotations outputted bu the current action. When the action is called directly from a workflow file from the repository, it very nicely displays the test errors in annotations, and the test output can be collapsed. 
![image](https://github.com/user-attachments/assets/41911f0e-cca1-44d2-b77b-cbe3a649fee2)

However, if the action is bundled in a reusable workflow (e.g. `resuable-workflow.yml`) and called in in action with:

```yaml
jobs:
  example:
    uses: ./.github/workflows/reusable-workflow.yml
```

In this case the annotation only provides a summary of the test-run, where the detailed test output information is not available. 

![image](https://github.com/user-attachments/assets/711fc629-cd59-4fbb-92ba-80479e01538e)

Is there any way where the annotations can be passed on from the reusable workflow to the main action scope?

**Comment by mikepenz** [comment]
Unfortunately, I am not aware of any special API to do this. As far as I know and can tell this is a behavior from GitHub.
If someone has an alternative solution I'd appreciate the input.

**Comment by mikepenz** [comment]
Closing as I believe this is not something that can be solved in the action. If somebody has a solution or an idea how to work around this, feel free to re-open or open a PR. Thanks
