### ISSUE TITLE
Show raw output for passed test

### ISSUE THREAD

**Issue by amanank** [mikepenz/action-junit-report#1162]
Anyway, to show the raw test output for the passed test?

I have enabled
```conf
          include_passed: true
          detailed_summary: true
          annotate_notice: true
```

I get annotations without much information:
<img width="440" alt="image" src="https://github.com/user-attachments/assets/5e71e36b-5950-476a-866b-5ed27e03d931">

I want to be able to see the `system-out` from the test report xml file

<img width="526" alt="image" src="https://github.com/user-attachments/assets/74c0204b-3065-4a02-ba02-db82dd26a607">

**Comment by mikepenz** [comment]
The action uses the `message` or falls back to the `error` of a test failure. 

System-out is not supported, and would usually also be too long to displayed. As you can see in the code:
https://github.com/mikepenz/action-junit-report/blob/main/src/testParser.ts#L432-L449

the stacktrace is also truncated to 2 lines only.
