### ISSUE TITLE
Bad regex causing failure

### ISSUE THREAD

**Issue by hlolli** [mikepenz/action-junit-report#12]
Thanks Mike Penz for fast response on my last ticket.

It seems that some new bug got introduced, which seems to me to be from the fork?

https://github.com/mikepenz/action-junit-report/blob/main/dist/index.js#L160

As you see here, this regex is taking the string for the name of the workflow, and I believe the + sign in c++ causes it to interfere with the regex. I'll try changing to cxx as a temporary workaround. An example of this failure you can see here:

https://github.com/csound/csound/actions/runs/492358430

ADDED: The test case containing "c++" isn't failing anymore and the action runs fine now, so it's only a problem for failing test cases.

**Comment by mikepenz** [comment]
Not sure this is introduced. As the same code already existed in the previous release: https://github.com/mikepenz/action-junit-report-legacy/blob/main/utils.js#L8

Let me see to add a test case in the demo data which contains a `+` sign
