### ISSUE TITLE
No report/summary generated when there are no passing tests and set to require passing tests

### ISSUE THREAD

**Issue by daantimmer** [mikepenz/action-junit-report#1215]
When all tests have failed in a given test run and when the setting to require at least one passing test results in no (detailed_)summary (as output) being generated.

I think this behaviour is not desired and a summary should be generated with all those tests that failed.

See return statement + comment: https://github.com/mikepenz/action-junit-report/blob/db71d41eb79864e25ab0337e395c352e84523afe/src/main.ts#L102

**Comment by mikepenz** [comment]
Good day. Thanks for the ticket. 

Can you please tell me more on your usecase? As this behaves as designed. 

If you just want to fail the action if there is a failure, and still see reports and everything you might wanna use `fail_on_failure` instead?

**Comment by daantimmer** [comment]
That indeed behaves in a way that works for us too. Was just surprised the parsing would stop at the given line to begin with :-)

**Comment by mikepenz** [comment]
Thanks for the answer. The reason his that it is considered a fatal error.
