### ISSUE TITLE
v5 release missing changelog

### ISSUE THREAD

**Issue by akervinen** [mikepenz/action-junit-report#1232]
https://github.com/mikepenz/action-junit-report/releases/tag/v5

Changelog generation for v5 seems to have picked the previous prerelease as the comparison point, leading to zero PRs to pull change information from.

**Comment by mikepenz** [comment]
@akervinen that is just the v5 tag which will shift around. the changelog itself can be found on the real release here: 
- https://github.com/mikepenz/action-junit-report/releases/tag/v5.0.0-rc01

(v5 is not yet fully release, the v5 tag was placed to ease people who want to get started with it already)

**Comment by TWiStErRob** [comment]
v5 is a stable tracking tag, it shouldn't be published unless the major is ready for consumption.

Renovate (and probably Dependabot too) will pick up the v5 tag:
![image](https://github.com/user-attachments/assets/00784aa2-e333-4d70-87f1-af331b9af25f)

Gradle did a similar maneuver a few months ago https://github.com/gradle/actions/issues/322

**Comment by TWiStErRob** [comment]
What are the actual breaking changes? Do we need to do anything between v4 and v5?

**Comment by mikepenz** [comment]
@TWiStErRob no breaking changes API wise, however the summary table was reformatted, to be less noisy and verbose. Also there is new support for having headers in the summary table based on the test suite.
