### ISSUE TITLE
Change icons to convey information

### ISSUE THREAD

**Issue by JayBazuzi** [mikepenz/action-junit-report#1262]
We love your test report *so* much that we spent our mob/ensemble session proposing ways we think could make it better.

# Problem

Color draws my eye. In the following screenshot my eye is brought to the red `Failed ❌`, even though there are no failures.

<img width="839" alt="image" src="https://github.com/user-attachments/assets/9ca6838f-031e-4827-bb81-350330c551f8">

# Proposed Solution

## Failing tests

Only show ❌ if there are failures:

<img width="167" alt="image" src="https://github.com/user-attachments/assets/6d8e93d8-611b-4dd4-98b1-2b784a092c41">
<img width="135" alt="image" src="https://github.com/user-attachments/assets/d122bfa2-a476-43d2-a2eb-96b12c7bf683">

## Skipped tests

- Change the icon from ⏭️ to ⚠️

The yellow draws my eye more, and lets me know this is something that could be a problem. It is also more consistent with coloring of other test frameworks.

- Only show skipped icon if there are skipped

<img width="177" alt="image" src="https://github.com/user-attachments/assets/178eda60-7879-43c4-9e60-e4a2a88444f3">
<img width="164" alt="image" src="https://github.com/user-attachments/assets/5b1fddd8-25e1-4564-8c02-866c021f42cf">

## Passing tests

Communicate more information by adding an additional icon:

- ✅: Everything passed with no failures
- ☑️: Some tests passed and some tests failed
- `<No icon>`: There were no passing tests.

<img width="470" alt="image" src="https://github.com/user-attachments/assets/5a510391-2e82-4618-835b-5892bbb79651">

<img width="480" alt="image" src="https://github.com/user-attachments/assets/b00e3cbe-e3ac-4332-9584-af14458e5fe4">

<img width="517" alt="image" src="https://github.com/user-attachments/assets/b009006c-66a6-4095-b183-214bb84feb59">

## Bonus - no tests run

If no tests run, use ❌. Notice how this compares to the last **Passing tests** example; we like this better.

<img width="778" alt="image" src="https://github.com/user-attachments/assets/41945d96-bbc8-472c-84db-d783ac3c9194">

Thanks,
- @jaybazuzi
- @4dsherwood
- @michaelrwolf
- @isidore
- @susanfung

**Comment by mikepenz** [comment]
Thank you very much @JayBazuzi  and everyone else linked at the bottom for highlighting these changes. 

Really appreciate the suggestions and I'll look into adopting parts (if not all) proposals.

**Comment by isidore** [comment]
Thanks so much for this!
