### ISSUE TITLE
Cannot capture test reports from a folder in the root? 

### ISSUE THREAD

**Issue by plusmobileapps** [mikepenz/action-junit-report#154]
# Overview 

I have written a [GitHub action for running unit tests with Kscript](https://github.com/plusmobileapps/kscript-action) and I was trying to get the reports to show up using this action. There are some limitations to running kscript unit tests in CI which essentially requires generating a temporary project in the root folder under a hidden folder `.kscript/`. So when I tried to use the following glob, `**/.kscript/*/build/test-results/test/TEST-*.xml`, it doesn't seem to capture the tests which I thought was correct after [testing it on an online glob tool](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2F.kscript%2F%2A%2Fbuild%2Ftest-results%2Ftest%2FTEST-%2A.xml&matches=false&tests=%2F%2F%20This%20will%20match%20as%20it%20ends%20with%20%27.js%27&tests=file%3A%2F%2F%2Froot%2F.kscript%2Fkscript_tmp_project__star-wars-char-enum.kts_1621146582555%2Fbuild%2Ftest-results%2Ftest%2FTEST-maintest.xml&tests=%2Ftest%2Fsome%2Fglobs). Below is a screenshot of where the files would live under the build folder and [here is the actual run](https://github.com/plusmobileapps/kotlin-scripting/pull/6/checks?check_run_id=2593584756#step:4:130) of the workflow with the path `file:///root/.kscript/kscript_tmp_project__star-wars-char-enum.kts_1621146863830/build/..`.

<img width="452" alt="Screen Shot 2021-05-15 at 23 45 59" src="https://user-images.githubusercontent.com/31364841/118388180-b6899c80-b5d7-11eb-96ae-ba1ade7bc0a2.png">

I was curious is this test report not being found because of how the [glob tool](https://github.com/actions/toolkit/tree/main/packages/glob) was being used in Junit report action or is there just a limitation to capturing files with a glob that live in the root folder?

**Comment by mikepenz** [comment]
@plusmobileapps I believe the problem may be that you store the files outside the project (as you write in the root) the action itself would search only within the project. 

You could copy over the files to the project directory so the action will access them

**Comment by plusmobileapps** [comment]
Ahh I see, so just sounds like a limitation of the glob not being able to search outside of the original project directory. I will try your suggestion of copying over the reports back to the project directory and close this issue out since it does seem like an issue with the unit test reporting action. Appreciate the help!

**Comment by plusmobileapps** [comment]
Just wanted to thank you @mikepenz for the suggestion, I was able to figure it out and get it working now by copying the test results back over to the project directory 🚀 

Linked the code here in case someone down the road ever runs into a similar issue.
