### ISSUE TITLE
How to handle multiple jobs with reports?

### ISSUE THREAD

**Issue by iBotPeaches** [mikepenz/action-junit-report#194]
So I like running our suite on multiple php version and various modules, but in research it appears the JUnit Test Report job only takes the last submitted one, so it appears to squash previous same job runs.

Maybe intended, but do you have any ideas on a path for this?

---
(php72 - module a)
```
  ℹ️ 894 tests run, 28 skipped, 1 failed.
  ℹ️ Posting status 'completed' with conclusion 'failure' to refs/heads/foo (sha: fa38e6da7e82f4e19e2f0c446bae36703592d653)
```

(php72 - module b)
```
  ℹ️ 1678 tests run, 51 skipped, 0 failed.
  ℹ️ Posting status 'completed' with conclusion 'success' to refs/heads/foo (sha: fa38e6da7e82f4e19e2f0c446bae36703592d653)
```

The JUnit Test Report that shows up on sidebar is green (despite 1 job failing) and the total count is - `1678 tests run, 51 skipped, 0 failed.` which matches the last run.

**Comment by iBotPeaches** [comment]
> Maybe intended, but do you have any ideas on a path for this?

I named the tests differently with `check_name` so that works. 

If I run like 20 parallel though, I get 20 additional sidebar items, so maybe a merge in some point would be cool.

**Comment by mikepenz** [comment]
Thank you very much for the report @iBotPeaches 

Using the `check_name` is indeed currently the preferred approach. 

Your suggestion to merge them together sounds like a great feature to add. Thank you.
