### ISSUE TITLE
Can the Junit report separate the stack trace onto multiple lines?

### ISSUE THREAD

**Issue by amandalewis-mfp** [mikepenz/action-junit-report#211]
I have a lot of repos in my org using this action junit report tool and they all print the stack trace on one line, in the format of an array of strings. I thought updating to v2 would solve this, but I see the same output. Is there any way yall could make a version or option to separate the stack traces onto multiple lines, or does this functionality exist already? We were using v1, and I have tried using v2 in one of our repos with no change.

**Comment by mikepenz** [comment]
Thank you for the report. 

Do you by coincidence have a sample repo / some open source repo to showcase the problem / behavior?

**Comment by amandalewis-mfp** [comment]
No, it looks like all our repos are private, so I can give you a screenshot?
![Screen Shot 2021-06-28 at 11 22 36 AM](https://user-images.githubusercontent.com/69917082/123670813-3a53bd00-d803-11eb-8656-d847d1b874dc.png)

**Comment by mikepenz** [comment]
@amandalewis-mfp thank you very much for the screenshots. I'll have a look into this

**Comment by mikepenz** [comment]
@amandalewis-mfp I believe in that case it's related to the test is reported. Looking at the demo tests included in this repo it shows that multi line outputs are done if applicable: https://github.com/mikepenz/action-junit-report/pull/224/files#annotation_1635973655

**Comment by amandalewis-mfp** [comment]
Hmm okay thanks anyway!
