### ISSUE TITLE
Pattern error when processing test results

### ISSUE THREAD

**Issue by ImOnMars** [mikepenz/action-junit-report#249]
I'm using RSpec with [RSpec Junit Formatter](https://github.com/sj26/rspec_junit_formatter) and KnapsackPro for parallelization of my tests, which I'm using on our Node frontend tests successfully, but it breaks with the backend RSpec tests when there's any test failures (the parallel containers that succeed create and display the report as expected) with the following message in the "Process test results" step:

`Error: Invalid pattern '**/./spec/models/group_spec.rb.*'. Relative pathing '.' and '..' is not allowed.`

I have no special configuration or logic, definitely none that involves pathing like that, and as noted the step that actually runs RSpec runs as intended both when there are failures and when there aren't.

**Comment by iBotPeaches** [comment]
I hit that while using the PHP Junit Formatter and couldn't figure it out, so cheated and just corrected it in a step before the test.
```
            - name: Fix Test Reports
              if: always()
              run: sed -i 's#\./##g' tests/backend/codeception/_output/report.xml
```

Hacky beyond belief, but I like you did not intentionally introduce any relative pathing. Its just how it worked.

**Comment by mikepenz** [comment]
@ImOnMars would you have some sample test results to include in the tests for this situation?

**Comment by ImOnMars** [comment]
> @ImOnMars would you have some sample test results to include in the tests for this situation?

@mikepenz Unfortunately this was long enough ago and we've since changed what library we're using for this so I can't provide any further info at the moment.

**Comment by mikepenz** [comment]
@ImOnMars no worries. Thank you for reporting back.


Closing this one for now. Anyone stumbling over it again, please either reopen, or create a new issue.

**Comment by cosmith** [comment]
Hello, I hit this too but the sed trick is working so no worries :)
