### ISSUE TITLE
Not sure about how this action works

### ISSUE THREAD

**Issue by thib3113** [mikepenz/action-junit-report#281]
Hello, 

I setup this action, and it "seems" to work : 
```
Run mikepenz/action-junit-report@v2
  with:
    report_paths: ./coverage/junit.xml
    require_tests: true
    token: ***
    check_name: JUnit Test Report
    fail_on_failure: false
📘 Reading input values
📦 Process test results
  test UnifiAuth fail test for junit:1 | Error: expect(received).toBeFalsy()
  test UnifiAuth fail test for junit:1 | Error: expect(received).toBeFalsy()
  ℹ️ 446 tests run, 0 skipped, 2 failed.
  ℹ️ Posting status 'completed' with conclusion 'failure' to https://github.com/thib3113/unifi-client/pull/141 (sha: 91110da18e541c228c15873c5e43438c877cacc0)
🚀 Publish results
```
![image](https://user-images.githubusercontent.com/5489218/129447066-a00cff69-254f-44e2-9dba-48bc497443cb.png)

But .... I didn't know what this action do ?

When checking the related PR : 
 - no comments on files
 - no comments in PR
 
 ( I only notice a new actions in github actions )

**Comment by mikepenz** [comment]
@thib3113 the action parses the error files and will try to discover the source file the error occurred for. 

This may fail though due to different reasons. The error report may contain a wrong source file or different path or similar, making the action to not be able to report at the proper location. 

When it is able to, it would look like: https://github.com/mikepenz/action-junit-report/runs/2872678571?check_suite_focus=true

**Comment by thib3113** [comment]
Hum, yes I've results like : https://github.com/mikepenz/action-junit-report/runs/2872678571?check_suite_focus=true

But not like this : https://github.com/mikepenz/action-junit-report/blob/main/.github/images/annotated.png 

But, because my junit.xml is not generated by junit ( but by an extension on jest test runner ), maybe it doesn't include the path ... ( the annotations juste say : Check failure on line 1 in test XXXX fail test for junit , and not filePath like yours )

**Comment by mikepenz** [comment]
yes that is most likely the problem. The action in this case won't be able to associate file + location to annotate. :/

**Comment by thib3113** [comment]
Ok, So I dig a little in the code, with a junit like : 
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="446" failures="2" errors="0" time="34.939">
  <testsuite name="UnifiAuth.test.ts" errors="0" failures="1" skipped="0" timestamp="2021-08-14T16:15:22" time="0.587" tests="42">
    <testcase classname="UnifiAuth.test.ts fail test for junit" name="UnifiAuth.test.ts fail test for junit" time="0.001">
      <failure>Error: expect(received).toBeFalsy()

Received: true
    at Object.&lt;anonymous&gt; (./tests/units/UnifiAuth.test.ts:911:22)
    at Promise.then.completed (./node_modules/jest-circus/build/utils.js:390:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (./node_modules/jest-circus/build/utils.js:315:10)
    at _callCircusTest (./node_modules/jest-circus/build/run.js:218:40)
    at _runTest (./node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (./node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (./node_modules/jest-circus/build/run.js:60:9)
    at run (./node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (./node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:166:21)</failure>
    </testcase>
  </testsuite>
</testsuites>
```

and parseFile return : 
```
{
  count: 446,
  skipped: 0,
  annotations: [
    {
      path: 'ts fail test for junit',
      start_line: 1,
      end_line: 1,
      start_column: 0,
      end_column: 0,
      annotation_level: 'failure',
      title: 'ts fail test for junit.UnifiAuth.test.ts fail test for junit',
      message: 'Error: expect(received).toBeFalsy()',
      raw_details: 'Error: expect(received).toBeFalsy()\n' +
        '\n' +
        'Received: true\n' +
        '    at Object.<anonymous> (./tests/units/UnifiAuth.test.ts:911:22)\n' +
        '    at Promise.then.completed (./node_modules/jest-circus/build/utils.js:390:28)\n' +
        '    at new Promise (<anonymous>)\n' +
        '    at callAsyncCircusFn (./node_modules/jest-circus/build/utils.js:315:10)\n' +
        '    at _callCircusTest (./node_modules/jest-circus/build/run.js:218:40)\n' +
        '    at _runTest (./node_modules/jest-circus/build/run.js:155:3)\n' +
        '    at _runTestsForDescribeBlock (./node_modules/jest-circus/build/run.js:66:9)\n' +
        '    at _runTestsForDescribeBlock (./node_modules/jest-circus/build/run.js:60:9)\n' +
        '    at run (./node_modules/jest-circus/build/run.js:25:3)\n' +
        '    at runAndTransformResultsToJestFormat (./node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:166:21)'
    }
  ]
}
```
So, it seems you lib try to get the path from the className, but for jest (jest-junit to be precise), className is a "test stack" ( describe => ... => it ), and not a filename (so doesn't work for my case) . Same for title . 

But, in fact, junit from jest-junit always have a root testsSuites with name "jest tests", and with a regex like : `/\n\s* at.*\(([a-zA-Z\.\/]+):([0-9]+):([0-9]+)\)\n/m` you can easily retrieve the file / the line, and the column . 

So, I didn't known if it's interessting to try to implement this function in this action ? Or not ?

**Comment by mikepenz** [comment]
Thank you for looking further into it. 

It seems interesting, but I fear that this is very particular to jest-junit and won't fully apply to other junit usecases, and may cause problems. 

it may be feasible for your usecase to fork this action and apply the custom regex for your needs and use the forked version instead?

**Comment by thib3113** [comment]
Hello, So I continue my research, and found some others actions, specialy for jest . 

So I think I will use them . ( I didn't have the time to maintain a fork of this project :/ ) .

**Comment by markstos** [comment]
I looked at this area as well and found that `eslint` sets `classname=` to a file path, but the Junit reporter from `mocha 8.1.3` sets the classname to a string that's the same as the "testsuite name". This seems like a bug or weakness with Mocha's Junit reporter. Since it already has the test suite name, there's no need to repeat it, but including the path of the test failure would bew valuable information!

**Comment by markstos** [comment]
I think I found a solution for Mocha, which is to switch to the `mocha-junit-circle-report` reporter, which sets a `file` property. 

From reading the source code here, it appears the `file` property is checked before trying to parse `classname`.  https://www.npmjs.com/package/mocha-junit-circle-report

Time for a meeting now, but I'll check on this later.
