### ISSUE TITLE
Check <testsuite> for `file` attribute

### ISSUE THREAD

**Issue by markstos** [mikepenz/action-junit-report#401]
The popular "mocha-junit-report" project attaches the `file` attribute to the `<testsuite>` tag, because Circle CI looks for it there. Test suites are not split over files, so it's waste of bytes to repeat the `file` attribute for every `<testcase>` within it.

https://github.com/michaelleeallen/mocha-junit-reporter/blob/master/index.js#L292

If there is `file` attribute on the current `<testcase>` use that, then next try the `file` attribute of the parent `<testsuite>`. Finally, fallback to trying to parse `classname` into a file. 

Here's the PR where `mocha-junit-reporter` proposed adding it five years ago:
https://github.com/michaelleeallen/mocha-junit-reporter/pull/41

**Comment by mikepenz** [comment]
Could you please provide a sample test result file we could include in the automated tests to investigate further?

**Comment by markstos** [comment]
@mikepenz Thanks for considering this. Here's XML generated by the popular `mocha-junit-reporter` project:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="3.2860" tests="15515" failures="0" skipped="1">
  <testsuite name="Root Suite" timestamp="2021-10-28T00:15:42" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Config files" timestamp="2021-10-28T00:15:42" tests="0" file="/path/test/config.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="default config" timestamp="2021-10-28T00:15:42" tests="1" file="/path/test/config.js" time="0.0000" failures="0">
    <testcase name="Config files default config projectUTCOffset should be a callable with current UTC offset" time="0.0020" classname="projectUTCOffset should be a callable with current UTC offset">
    </testcase>
  </testsuite>
</testsuites>
 ```

The paths in the `file` attribute are absolute.

**Comment by mikepenz** [comment]
@markstos do you coincidentally have also a result with failures? Thank you very much

**Comment by mikepenz** [comment]
I've created a PR to add this, could you please verify it matches your expectation for mocha reports: 
https://github.com/mikepenz/action-junit-report/pull/402
