### ISSUE TITLE
Listing succeeded tests

### ISSUE THREAD

**Issue by pun-ky** [mikepenz/action-junit-report#42]
Right now, seems that this action is listing tests with errors, however, as a build user, I want to be able to review which tests were effectively analyzed so that it would be great if tests that ended with success will be also printed but with green indicator ;) It would be nice to have such an input parameter that will control that. Still, the way in which the action is working actually could remain as default.

I've got only:

![image](https://user-images.githubusercontent.com/10673561/107757371-c0280d80-6d25-11eb-96b4-5b9734f170a4.png)

**Comment by mikepenz** [comment]
I wonder how good that is gonna scale. as there are rate limits to keep in mind. and let's say you have 1000 tests, updating github with all of them will most likely fail due to the rate limit.

**Comment by pun-ky** [comment]
Hmm still having it as option to test if configured everything correctly might be considered useful. Now it is kinda black box 😁

**Comment by kesselborn** [comment]
Summary is rendered as markdown on the overview page. As a work around I create a markdown document with a table listing all tests and set this as a summary.

It's hacky as the markdown is multiline but output variables must be single line (therefore the conversions below).


      - name: Create Test Report Summary
        id: test_summary
        run: |
          # generate a markdown document called results.md

          export SUMMARY="$(cat results.md)"

          # we need to do some conversions in order to get a one-liner:
          SUMMARY="${SUMMARY//'%'/'%25'}"
          SUMMARY="${SUMMARY//$'\n'/'%0A'}"
          SUMMARY="${SUMMARY//$'\r'/'%0D'}"

          # save document in output variable which can be used in action-junit-report
          echo "::set-output name=summary::$(echo "$SUMMARY")"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'results.xml'
          check_name: Test Report
          fail_on_failure: true
          require_tests: true
          summary: ${{ steps.test_summary.outputs.summary }}

This is how it looks like:

![image](https://user-images.githubusercontent.com/12173/132840993-696c2167-cae6-4a83-900f-2b287d4f7be0.png)




I left out the generation of the markdown as my original report is from `cargo test -- --format=json > results.json` ... but just in case somebody has this same setup (this kind of makes it even more hackish, sorry :D )

          # cargo output has some nasty combination of escape characters which confuse bash
          sed -i.bak -e 's/\\"//g' results.json

          echo "|  |test  |duration|" >  results.md
          echo "|--|------|--------|" >> results.md
          while read line
          do
              echo "${line}"|jq -r 'if .event != "started" and .type != "suite" and .event == "ok" then ["|","✅|", .name,"|",(.exec_time|tostring),"s","|"]|add else empty end'
              echo "${line}"|jq -r 'if .event != "started" and .type != "suite" and .event == "failed" then ["|","❌|", .name,"|",(.exec_time|tostring),"s","|"]|add else empty end'
              echo "${line}"|jq -r 'if .event != "started" and .type != "suite" and .event == "ignored" then ["|","🙈|", .name,"|",(.exec_time|tostring),"s","|"]|add else empty end'
              echo "${line}"|jq -r 'if .event != "started" and .type != "suite" and .event == "timeout" then ["|","⌛️|", .name,"|",(.exec_time|tostring),"s","|"]|add else empty end'
              echo "${line}"|jq -r 'if .event != "started" and .type != "suite" and .event == "allowed_failure" then ["|","🤷‍|", .name,"|",(.exec_time|tostring),"s","|"]|add else empty end'
          done < results.json >> results.md
