### ISSUE TITLE
Different line number representation

### ISSUE THREAD

**Issue by JonatanAntoni** [mikepenz/action-junit-report#429]
Hi @mikepenz,

We are using your Action to attach test results to our repositories e.g., https://github.com/ARM-software/VHT-GetStarted/blob/main/.github/workflows/basic.yml.

It looks like there are different ways to note file and line number information. In above example our test execution results in the following result:
```xml
<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="1" tests="4" time="0.0">
	<testsuite disabled="0" errors="0" failures="1" name="Cloud-CI basic tests" skipped="0" tests="4" time="0">
		<testcase name="test_my_sum_pos" file="main.c" line="44"/>
		<testcase name="test_my_sum_neg" file="main.c" line="45"/>
		<testcase name="test_my_sum_fail" file="main.c" line="38">
			<failure type="failure" message="Expected 2 Was 0"/>
		</testcase>
		<testcase name="test_my_sum_zero" file="main.c" line="47"/>
	</testsuite>
</testsuites>
```

Each test case has dedicated attributes for `file` and `line`. But the failure of this result is attached to line 1 of `main.c`:
![image](https://user-images.githubusercontent.com/25795816/143855218-70425f06-3ac6-4999-a20f-cd162551793a.png)

Inspecting your implementation let me think you are expecting the file/line information in a different way i.e., `file="main.c:38"`. Is that understanding correct? It looks like the JUnit XML format is interpreted differently. Is it possible to support both formats? 

Thanks,
Jonatan

**Comment by mikepenz** [comment]
@JonatanAntoni thank you very much for the report. 

We do support different variations of JUnit (like) outputs. Many of the existing formats and sample test reports we do have in the tests do not include the line number. 

The `:` based formatting was added to handle the `rust` style output as described here: https://github.com/mikepenz/action-junit-report/pull/360

Given your above sample output it seems like a good addition though to also handle this kind of line number annotation. 
Will have a look at this. 

Cheers,
Mike

**Comment by mikepenz** [comment]
@JonatanAntoni created a new release 2.8.1 which includes handling the `line` attribute of the xml if available. 

And also included the xml you included in the report as a new test case.

**Comment by JonatanAntoni** [comment]
Thanks @mikepenz, that was really fast! I was still thinking about raising a PR to contribute that.
I confirm the release 2.8.1 works for us as expected. Many thanks again.

**Comment by mikepenz** [comment]
@JonatanAntoni thank you so much, really appreciating your support :)
