### ISSUE TITLE
Failing to report results when output contains non ascii characters

### ISSUE THREAD

**Issue by seppo0010** [mikepenz/action-junit-report#440]
Hello there. Thanks for this action, is great.

I noticed that my tests failed to be published when their report contained emojis. The error I got was the following:

```
  Error: ❌ Failed to create checks using the provided token. (HttpError: Validation Failed: {"resource":"CheckRun","code":"invalid","field":"annotations"})
  Warning: ⚠️ This usually indicates insufficient permissions. More details: https://github.com/mikepenz/action-junit-report/issues/23
```

I'm not sure it is a problem on this action or on github results, though.

Thanks.

**Comment by seppo0010** [comment]
Enabling debug output it seems like the annotation looks correct. It might be a problem in the github end?

![image](https://user-images.githubusercontent.com/223776/144847763-9e11276d-e2f8-483e-a580-604863e7eb42.png)

**Comment by mikepenz** [comment]
Thank you very much for the report, will investigate

**Comment by mikepenz** [comment]
I had a spin on this, but couldn't yet figure out a way to make it work. 

A more or less temporary solution would be to drop emoji sequences, so it won't make the import fail. 

It's also strange as it would work if the emoji is specified via the action itself, but not if read in from the xml report. 
There must be some encoding issue somewhere. 

If anyone knows what possibly could be the cause, any help would be appreciated.
