### ISSUE TITLE
Source file autodiscover and Python bytecode

### ISSUE THREAD

**Issue by mgsalas** [mikepenz/action-junit-report#452]
Hi, I was checking out this action and decided to give it a try with a simple python package, but I noticed that the annotations are being done on the wrong file. More specifically it's taking `*.pyc` files instead of the original source file.

Is there any way to ensure it doesn't look inside the `__pycache__` directories or something similar?

I guess one workaround would be to clean all the bytecode before running the action, but I wonder if is possible to handle this case within the action itself.

Here's an example run for reference: https://github.com/mgsalas/python-junit-test/runs/4567244112?check_suite_focus=true

**Comment by mikepenz** [comment]
@mgsalas good input. Currently only `/build/` directories are excluded, will add a new configuration to provide more manual inputs. 

https://github.com/mikepenz/action-junit-report/blob/main/src/testParser.ts#L109
