### ISSUE TITLE
Not getting line numbers from mocha tests via web-test-runner

### ISSUE THREAD

**Issue by bennypowers** [mikepenz/action-junit-report#458]
Hello! Thank you for providing this action.

I wrote a [junit reporter for web-test-runner](https://github.com/modernweb-dev/web/tree/master/packages/test-runner-junit-reporter) which outputs xml like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Chromium_playwright_/elements/pfe-accordion/test/pfe-accordion.spec.ts" id="0" tests="12" skipped="0" errors="2" failures="2" time="0.006">
    <properties>
      <property name="test.fileName" value="/Users/bennyp/Developer/patternfly-elements/elements/pfe-accordion/test/pfe-accordion.spec.ts"/>
      <property name="browser.name" value="Chromium"/>
      <property name="browser.launcher" value="playwright"/>
    </properties>
    <testcase name="expands the middle panel" time="0.001" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header Space"/>
    <testcase name="expands the middle panel" time="0" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header Enter"/>
    <testcase name="moves focus to the link in middle panel" time="0.003" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header Tab">
      <failure message="expected &lt;pfe-accordion-header aria-controls=&quot;&quot; pfelement=&quot;&quot; class=&quot;PFElement&quot; on=&quot;null&quot; id=&quot;pfe-accordion-8vcn1owsc&quot; has_body=&quot;&quot; has-body=&quot;&quot; heading-text=&quot;Incididunt in Lorem voluptate eiusmod dolor?&quot; heading-tag=&quot;h3&quot; disclosure=&quot;false&quot;&gt;
      &lt;h3&gt;Incididunt in Lorem voluptate eiusmod dolor?&lt;/h3&gt;
    &lt;/pfe-accordion-header&gt; to equal &lt;a href=&quot;#&quot;&gt;Lorem ipsum dolor sit amet&lt;/a&gt;" type=""><![CDATA[  at o.<anonymous> (elements/pfe-accordion/test/pfe-accordion.spec.ts:663:44)]]></failure>
    </testcase>
    <testcase name="moves focus to the link in first panel" time="0" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header Shift+Tab">
      <failure message="expected &lt;pfe-accordion-header id=&quot;header1&quot; aria-controls=&quot;panel1&quot; pfelement=&quot;&quot; class=&quot;PFElement&quot; on=&quot;null&quot; has_body=&quot;&quot; has-body=&quot;&quot; heading-text=&quot;Consetetur sadipscing elitr?&quot; heading-tag=&quot;h3&quot; disclosure=&quot;false&quot;&gt;
      &lt;h3&gt;Consetetur sadipscing elitr?&lt;/h3&gt;
    &lt;/pfe-accordion-header&gt; to equal &lt;a href=&quot;#&quot;&gt;Lorem ipsum dolor sit amet&lt;/a&gt;" type=""><![CDATA[  at o.<anonymous> (elements/pfe-accordion/test/pfe-accordion.spec.ts:674:44)]]></failure>
    </testcase>
    <testcase name="moves focus to the last header" time="0" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header ArrowDown"/>
    <testcase name="moves focus to the first header" time="0" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header ArrowUp"/>
    <testcase name="moves focus to the first header" time="0" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header Home"/>
    <testcase name="moves focus to the last header" time="0" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header End"/>
    <testcase name="collapses the second panel" time="0.001" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header and the second panel is expanded Space"/>
    <testcase name="collapses the second panel" time="0" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header and the second panel is expanded Enter"/>
    <testcase name="moves focus to the link in the second panel" time="0" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header and the second panel is expanded Tab"/>
    <testcase name="moves focus to the first header" time="0.001" classname="&lt;pfe-accordion&gt; keyboard accessibility when focus is on the middle header and the second panel is expanded Shift+Tab"/>
  </testsuite>
</testsuites>
```
This XML contains line and file data in the CDATA comment of the `failure` element. However, although the github action does create annotations (see https://github.com/patternfly/patternfly-elements/runs/4599306749), it does not add file and line data to them. 

Is this a problem with the xml I'm writing with `@web/test-runner-junit-reporter`, or can we improve the action's parser?

Thanks

**Comment by mikepenz** [comment]
The best would be if it could output the line similar to this xunit report: https://github.com/mikepenz/action-junit-report/blob/main/test_results/xunit/report.xml#L4 So it will be the clearest for the action to identify line number. 

If it is provided in a different format, you can see the regex logic here which would try to parse uncover the line number: https://github.com/mikepenz/action-junit-report/blob/main/src/testParser.ts#L49-L55

**Comment by bennypowers** [comment]
Thanks @mikepenz I'll first take a look at my output to see how i can improve it, and if that's not workable i'll ping you here about modifying the actions' parser

**Comment by bennypowers** [comment]
the `file` and `line` attrs aren't mentioned in [IBM's junit xml schema](https://www.ibm.com/docs/en/developer-for-zos/9.1.1?topic=formats-junit-xml-format) can you refer me to a spec doc that includes them?

**Comment by mikepenz** [comment]
@bennypowers yes, that's correct. I couldn't find an official spec either for it to be included. 

But based on different report formats having it like this proofed to be the most consistent and secure way to get the line number. 
This was contributed via this format shown here in form of a xunit test report: https://github.com/mikepenz/action-junit-report/blob/main/test_results/xunit/report.xml#L4

We surely can also go the more tricky path to refine the parser. For that the easiest would be to run the tests locally and pass in the sample test exports from your reporter. 

Generally always expanding our test cases with different report formats to keep sure all of them are properly working :)

**Comment by bennypowers** [comment]
Great. Please take a look at the `expected.xml` files in https://github.com/modernweb-dev/web/pull/1824. If those already work with the action, we're ready to go

**Comment by mikepenz** [comment]
I'll probably not be able to come to that today due to the holidays, but I'll try to have a look in the next few days. Hope that's early enough?  

Thank you very much.

**Comment by bennypowers** [comment]
Of course, it's no rush. Enjoy your holiday

**Comment by mikepenz** [comment]
Found a few mins in-between :) 

thank you so much. You too!

Added your `expected.xml` as new testcase here: https://github.com/mikepenz/action-junit-report/runs/4626213715?check_suite_focus=true

the line number is properly used. 
You can see the test case + PR here: https://github.com/mikepenz/action-junit-report/pull/464

https://github.com/mikepenz/action-junit-report/pull/464/files#diff-7e8670dee8014834b8a492f48380862706e856032dd2d978ef91cd5ad2103fe2R469-R483

**Comment by bennypowers** [comment]
Thank you so much for the interest
