### ISSUE TITLE
Annotation title is empty when check_title_template is not passed

### ISSUE THREAD

**Issue by samsit258** [mikepenz/action-junit-report#470]
I found that in the annotation array, title is empty string when `check_title_template` is not passed as input.
<img width="849" alt="Screenshot 2021-12-31 at 23 07 55" src="https://user-images.githubusercontent.com/49629382/147829864-3b8d39f1-32d9-41f9-a4ad-5bcfd207a6cc.png">

After some digging, I believe action input is of type `string`
https://github.com/actions/toolkit/blob/daf8bb00606d37ee2431d9b1596b88513dcf9c59/packages/core/src/core.ts#L119-L140

And `checkTitleTemplate` should be `''` instead of `undefined`
https://github.com/mikepenz/action-junit-report/blob/b934b2768e8176903c8316b39c486fdf9942a970/src/testParser.ts#L263-L280

**Comment by mikepenz** [comment]
Thank you so much @samsit-coherent
