### ISSUE TITLE
New Feature: Published Report Includes Passed Tests

### ISSUE THREAD

**Issue by kenzie-rasmussen** [mikepenz/action-junit-report#487]
First off, wanted to say that I love this action, and I really appreciate your work!

I noticed in my builds that the action was taking in a 'secret' input called `include_passed` in the action as false, so I decided to set it to  'true' and see what happened.

My Test Report looked like this:

![image](https://user-images.githubusercontent.com/76795452/150850110-3bc5458b-f732-4c78-99b8-252f25f3c024.png)
![image](https://user-images.githubusercontent.com/76795452/150850173-5c6e44b7-087b-499c-a9a5-37c2d7537c22.png)

I think it's awesome that it lists all the tests! The only problem is that it includes the successful tests in the number of failed tests at the top (aka include_passed).

 I was wondering if a new feature could be created that would alter this input's effect on the test report, removing them from the failed count and maybe changing their natural grey check notice button to be a green checkmark? That way if the include_passed input was set to false, it would only show the failed tests, and if set to true it would show the passed, skipped, and failed ones? This would make the report much more comprehensive (and become my favorite thing ever.)

**Comment by mikepenz** [comment]
According to the GitHub documentation sadly it can only either be `failed`, a `warning` or a `notice`
<img width="598" alt="Screenshot 2022-01-26 at 13 25 05" src="https://user-images.githubusercontent.com/1476232/151162549-a767edb3-926a-4a3a-a703-4b6927212dd8.png">

**Comment by kenzie-rasmussen** [comment]
Sad to hear about the lack of green annotation - but it looks like you updated the overall test count! Im excited about that - will I need to use a new version in my workflows for that feature or will it be added to the current version?

**Comment by mikepenz** [comment]
There will be a new update of this action soon :) 

Haven't had time to release it yet, as there is one other item we may include
