### ISSUE TITLE
test report displays red check when using include_passed

### ISSUE THREAD

**Issue by kenzie-rasmussen** [mikepenz/action-junit-report#498]
Hello Again!

Love the update where my passed tests are not counted as failures! I also know that the annotations on the passed ones need to be grey. 

I was wondering if it's possible to change the button of the test report. Upon a successful job, the button should be green. Ideally with a test report that has no failures, the button should be green too. 

Currently, even if all the tests are passed, it still turns the button red:
![image](https://user-images.githubusercontent.com/76795452/152438781-e074b2be-ca61-4d1e-9bc5-89e345eedcec.png)

Could that button be upgraded to be green upon the lack of failed tests?

Thanks for all the work you do!

**Comment by kenzie-rasmussen** [comment]
Behold the beauty that is v2.9.1:

![image](https://user-images.githubusercontent.com/76795452/152553316-00345e21-fd6b-48f5-9311-cbf141f317f1.png)

Thank you so much for a quick response and straightforward fix! So excited to use this in my daily workflows

**Comment by mikepenz** [comment]
@kenzie-rasmussen thank you so much! Really appreciate your feedback and your sponsor :) 
Have a great weekend.
