### ISSUE TITLE
Test report fails to load if there are annotations

### ISSUE THREAD

**Issue by anhan32** [mikepenz/action-junit-report#672]
Hello,
The JUnit Test Report fails to load if there are annotations on the test results.

The annotations appear on the job summary page ok, but when I try to open the test report, I get an "Oops" page from GitHub with a 500 response code.
Annotations on passed and failed tests cause this error. If there are no annotations, meaning all tests pass and `annotate_notice` is set to `false`,  I can open the test report. 

I believe this was working last week.

Is there a way to disable annotations on failed tests to unblock us so that we can view the test report?

**Comment by mikepenz** [comment]
@anhan32 how many test-cases do you have? maybe it exceeds the amount of annotations github can handle. 

Please note that the `annotate_notice` only controls annotations for successful testcases. 

Disabling it will still result in annotations being created for test failures

**Comment by anhan32** [comment]
> how many test-cases do you have? maybe it exceeds the amount of annotations github can handle.

20 tests, and 1 was failing at the time that was annotated.

> Please note that the annotate_notice only controls annotations for successful testcases.

> Disabling it will still result in annotations being created for test failures

Yup understood. I was using it as a controlled use case where the test report works and then doesn't work

**Comment by mikepenz** [comment]
@anhan32 ok. for 20 tests it should really not cause problems. As I see it working for much larger cases. 

This could be a problem on GitHub itself maybe, as there is really no reason for it to not load for that amount. 

For example the testcase here: https://github.com/mikepenz/action-junit-report/actions/runs/2991279127 loads normally

**Comment by anhan32** [comment]
If you click on a specific job, it fails. For example https://github.com/mikepenz/action-junit-report/actions/runs/2991279127/jobs/4796481690

**Comment by mikepenz** [comment]
Oh wow. That's helpful. I'll investigate, and see if it may be due to a change we control

**Comment by anhan32** [comment]
Ok, thanks for your quick response!

**Comment by anhan32** [comment]
hey @mikepenz , it looks like this has been resolved. do you know what the problem was?

**Comment by mikepenz** [comment]
@anhan32 I sadly don't but given that the previous broken link works, it looks like this has been an issue on the GitHub side.
