### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by petrdvorak** [mikepenz/action-junit-report#712]
An API change in GitHub Actions deprecates the `set-output` action. The current implementation results in warnings in the run output:

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by petrdvorak** [comment]
OK, looking at recent repo commits, this seems already fixed, and we only need to wait for the new release.

**Comment by mikepenz** [comment]
Thank you very much for the report @petrdvorak 

Aiming to have a new tag created soon. With the latest octokit/rest updates.

**Comment by mikepenz** [comment]
`v3.5.2` was released
