### ISSUE TITLE
Get test report results in workflow logs as well

### ISSUE THREAD

**Issue by itsankit-google** [mikepenz/action-junit-report#720]
Hi, I recently switched from using https://github.com/ScaCap/action-surefire-report to this action,

Due to this existing issue with GitHub - https://github.com/mikepenz/action-junit-report/issues/40, this feature of including test results in the workflow logs was really helpful in `ScaCap/action-surefire-report`.

ref - 
![image](https://user-images.githubusercontent.com/88528384/196521437-9daf0a8d-823c-41c7-9ae8-b6f5cfadc3b4.png)

But I cannot find something like this in this action. Is there a flag to enable it??

**Comment by itsankit-google** [comment]
Okay, I see it shows the count here -
![image](https://user-images.githubusercontent.com/88528384/196526791-af2c257b-43a1-4f47-a9ea-d6adb4d6a5fa.png)

Will it also show the names of failed tests here, if any??

**Comment by mikepenz** [comment]
@itsankit-google while there is currently no flag to display the results as part of the logs one alternative to the reports which may end up in the wrong section, is the new `Job summary` feature GitHub offers. - https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

This will build a report with tables highlighting passed and failed tests. Offering also options to have a full result listing or only a simple overview:

<img width="956" alt="Screen Shot 2022-10-18 at 22 32 18" src="https://user-images.githubusercontent.com/1476232/196537939-dd91f90f-d6e0-431a-89ac-552e4a30c24b.png">

**Comment by itsankit-google** [comment]
Hi @mikepenz, If I understand correctly `Job Summary` will be attached to the correct build summary by the action even though test report might get attached to some wrong build, is that what you intended?

**Comment by itsankit-google** [comment]
![image](https://user-images.githubusercontent.com/88528384/196546213-802d4a4e-abfb-4308-9984-89543b281574.png)
Even though `detailed_summary` and `job_summary` are set to `true`. I only see this much detail in the test report, is this expected?

**Comment by mikepenz** [comment]
@itsankit-google the issue outlined in #40 (based on all information available) is something we can't yet fix. 

But GitHub introduced `Job Summaries` which are always attached to the particular job a given action was executed in. 
While this won't solve #40 and it's no direct answer to have the result in the logs (there is currently no flag to enable report via logs - as in my experience that should be the last resort for engineers to look into) - Using the job summary would help to get the insight into the results as part of the build. 

You can find it in action here for example: https://github.com/mikepenz/action-junit-report/actions/runs/3248491905#summary-8888055040

**Comment by itsankit-google** [comment]
> @itsankit-google the issue outlined in #40 (based on all information available) is something we can't yet fix.
> 
> But GitHub introduced `Job Summaries` which are always attached to the particular job a given action was executed in. While this won't solve #40 and it's no direct answer to have the result in the logs (there is currently no flag to enable report via logs - as in my experience that should be the last resort for engineers to look into) - Using the job summary would help to get the insight into the results as part of the build.
> 
> You can find it in action here for example: https://github.com/mikepenz/action-junit-report/actions/runs/3248491905#summary-8888055040

Thanks @mikepenz for the explanation.

**Comment by mikepenz** [comment]
Would that be a good fit for your requirements, or do you still believe having similar output in the console log itself may be needed?

**Comment by itsankit-google** [comment]
It works for me as of now because ultimately I want a way to know which tests failed if the report got lost due to any reason. Thanks!! Really appreciate your effort.

**Comment by itsankit-google** [comment]
Sometimes what happens is the tests log output is too verbose but an output like this with the reason in crisp why the tests failed really helps!!

![image](https://user-images.githubusercontent.com/88528384/196705033-ab4430e1-d1cb-4040-889a-a01eec944fe0.png)
