### ISSUE TITLE
Allow turning off warning annotations for no included tests

### ISSUE THREAD

**Issue by uriariel** [mikepenz/action-junit-report#742]
It would be helpful to add a flag that would allow turning off warning annotation if there are no failing tests and `include_passed` is `false`.

```      if (annotations.length === 0) {
        core.warning(
          `⚠️ No annotations found for ${testResult.checkName}. If you want to include passed results in this table please configure 'include_passed' as 'true'`
        )```

**Comment by uriariel** [comment]
@mikepenz #743 doesn't resolve this issue, I meant adding an option that will allow silencing those alerts even if `include_passed` is false.

**Comment by mikepenz** [comment]
Will lower it to `info` - https://github.com/mikepenz/action-junit-report/pull/746
Adding an additional config flag which needs to be maintained currently doesn't seem to fit into the action

**Comment by uriariel** [comment]
@mikepenz Thanks!
