### ISSUE TITLE
Workflow cancel does not work

### ISSUE THREAD

**Issue by achsvg** [mikepenz/action-junit-report#748]
Hello,

The workflow cancel on gha does not seem to work when running action-junit-report. Sometimes when all my tests are failing the report process is very slow so I tried to cancel the workflow but it does not work. I had to ssh into my build machine and manually kill the process.

Any solution for this?

**Comment by mikepenz** [comment]
Thank you for the ticket. Looked into the GitHub actions API. There does not look to be an API to check if the CI was cancelled. 
So I fear there is no direct way to react to the cancel operation.
