### ISSUE TITLE
Option to not parse the annotations if number of failures is high

### ISSUE THREAD

**Issue by demuux** [mikepenz/action-junit-report#760]
Hello!

I have test runs with thousands of failures (framework upgrade 🙄), and in this case reporting test results takes a long time (> 20 min, could be even more as I just cancel the workflow after that time).
By log output, I've found that it spends all that time in [`parseSuite` function here](https://github.com/mikepenz/action-junit-report/blob/d507ab47ffeb036bd3671233143d8026470aa955/src/testParser.ts#L337-L349), building annotations. 
And as far as I understand, currently there's no option to skip building annotations.

Ideally, it would be great to have some option like `annotations_limit = 50`, and for parser to exit early if the number of parsed annotations is more than the limit. And then just report the summary with the number of total failures.

**Comment by mikepenz** [comment]
Hello

Thank you very much for the future suggestion. 

That's a great idea. 

It could also help to solve: https://github.com/mikepenz/action-junit-report/issues/748#issue-1465101794
