### ISSUE TITLE
Weird behavior with multiple `report_paths` and failures not being processed

### ISSUE THREAD

**Issue by tiagobento** [mikepenz/action-junit-report#794]
Hi!

I'm seeing some weird behavior, where `Process test results` only prints test case names of the first glob I input to `report_paths`. 
More than that, it looks like this actions is not correctly failing the job when there's a failure.

Here's my job that should've reported error at the "Check test results (`main` only)" step.
https://github.com/tiagobento/kie-tools/actions/runs/4177206528

There are failures on `packages/**/dist-tests/junit-report*.xml` and `packages/**/dist-it-tests/junit-report*.xml`, but only reports on `packages/**/dist-it-tests/junit-report*.xml` are being listed (because it's the first one on the `report_paths` configuration).

Please let me know if you need more details so I can help you find a solution!

Thanks!!

**Comment by mikepenz** [comment]
Thank you very much for the report

@tiagobento would it be possible to rerun this build with `Debug logs`? 

It would show if we iterate through the respective configurations: https://github.com/mikepenz/action-junit-report/blob/main/src/testParser.ts#L405

**Comment by tiagobento** [comment]
@mikepenz Done -> https://github.com/tiagobento/kie-tools/actions/runs/4177206528/jobs/7280165151

**Comment by mikepenz** [comment]
Thank you very much. That is very helpful. I'll give it a closer look the next days.

**Comment by mikepenz** [comment]
Opened a PR with a fix for this (based on the debug logs)
