### ISSUE TITLE
Editor points out that github_token is required

### ISSUE THREAD

**Issue by mas0061** [mikepenz/action-junit-report#830]
I don't think github_token is required, but it is still "required: true" in actions.yml, which is pointed out by the editor.
If it is not required, I think it should be "required: false", is there any reason why it should be true?

<img width="567" alt="image" src="https://user-images.githubusercontent.com/931749/229027105-c044f7c5-e806-452c-bf5a-1f088508c0fb.png">

**Comment by mikepenz** [comment]
Thank you very much for the report!
