### ISSUE TITLE
Skipped tests are show as passed when included_passed set to true

### ISSUE THREAD

**Issue by gokhan-oner** [mikepenz/action-junit-report#844]
Summary section show the skipped tests correctly but in details, if you enabled showing passed tests, skipped tests shows as passed.

**Comment by mikepenz** [comment]
Do you have an example? Perhaps with a link or with screenshots of the outputs

**Comment by gokhan-oner** [comment]
@mikepenz its visible in the code: here- >https://github.com/mikepenz/action-junit-report/blob/62e35805fd1eebe1be9a870b2dc778f3d3e4740a/src/annotator.ts#LL152C1-L155C106 , header counts skipped & show then correctly.

Here in the details table, https://github.com/mikepenz/action-junit-report/blob/62e35805fd1eebe1be9a870b2dc778f3d3e4740a/src/annotator.ts#LL152C1-L155C106, check is either pass or fail, so in the details table, since skipped tests are not failed, it marked as passed, so you cannot see which tests is skipped.
I can open a PR & fix it

**Comment by mikepenz** [comment]
@gokhan-oner I'd really appreciate a PR if you already got the details. 

Was quite busy the last few days, so I couldn't yet have a closer look. 

Looks your last comment links to the same source twice.
