### ISSUE TITLE
action using deprecate 'set-output' command 

### ISSUE THREAD

**Issue by zibenua** [mikepenz/action-junit-report#854]
The action mikepenz/action-junit-report@v3.7.6 is using a deprecated 'set-output' command.
The log is showing the following warning twice : Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Can this be changed as mentioned in https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ ?

**Comment by mikepenz** [comment]
Are you certain this warning is outputed by the action? Do you have a screenshot of your build where this is logged?

I use this action myself, and don't see this warning.

**Comment by mikepenz** [comment]
there is no deprecated output for the action: https://github.com/mikepenz/action-junit-report/actions/runs/4964462475 

There may be something else in your pipeline showing this output
