### ISSUE TITLE
Documentation for Maven Surefire

### ISSUE THREAD

**Issue by arcuri82** [mikepenz/action-junit-report#866]
Hi, 
 thanks for this GitHub Action. I ended up here because I tried ScaCap, but [didn't work](https://github.com/ScaCap/action-surefire-report/issues/161). 
In your readme, you might want to add some documentation for running this action for Maven, in particular by specifying:

```
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
```

**Comment by mikepenz** [comment]
Good day. 

The Readme describes the `report_paths` taking any glob expression to junit format report paths: https://github.com/mikepenz/action-junit-report#inputs which is meant to be describing usecases with any path there may be.

**Comment by arcuri82** [comment]
hi,
 thanks for the quick response. Giving some examples of common cases (eg Maven) make it easier to start with this action, as a new user can just copy&paste the configuration when trying out this action. Something as simple as *If you are using Maven Surefire, you can set this variable to `**/target/surefire-reports/TEST-*.xml`* would be already of great help
