### ISSUE TITLE
Documentation: GITHUB_TOKEN

### ISSUE THREAD

**Issue by bittelc** [mikepenz/action-junit-report#91]
It would be awesome if you could describe in the README what permissions the input `GITHUB_TOKEN`. Eg. does it need full repo access?
<3

**Comment by mikepenz** [comment]
@bittelc thanks for the input. 

The action currently requires the permission to be able to create the checks: https://github.com/mikepenz/action-junit-report/blob/main/src/main.ts#L74

The `GITHUB_TOKEN` provided by actions is the default one provided by actions usually sufficient for these actions. 

You can find a detailed overview here: 
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token

**Comment by bittelc** [comment]
Ah duh, thank you so much!
