### ISSUE TITLE
act error: Error: The runs.using key in action.yml must be one of: [composite docker node12 node16], got node20

### ISSUE THREAD

**Issue by renepyo** [mikepenz/action-junit-report#942]
When using mikepenz/action-junit-report@v4

act -j build complains about the following:

Error: The runs.using key in action.yml must be one of: [composite docker node12 node16], got node20

It works for v3 though.

**Comment by mikepenz** [comment]
@renepyo seems act requires to be updated. -> https://github.com/nektos/act/pull/1988

GitHub actions retrieved support for `node20` around 1 month ago, which this action uses now.

**Comment by renepyo** [comment]
@mikepenz  - to be sure, do I need to update act?

**Comment by mikepenz** [comment]
@renepyo that question is best raised in the nektos/act repository.

**Comment by mikepenz** [comment]
But I suppose you will have to update the used action docker container
