### ISSUE TITLE
 Invalid character entity when using with dastardly

### ISSUE THREAD

**Issue by JonLittleIT** [mikepenz/action-junit-report#943]
Retrieved 1 reports to process.
  Error: Invalid character entity
  Column: 779
  Char: ;

when using with burp dastardly this error occurred. 

normally it works really good when ran. This broke in the last 30 days.

![image](https://github.com/mikepenz/action-junit-report/assets/22354862/80e01ad6-c18e-4601-a73d-468358e7e5c1)

**Comment by mikepenz** [comment]
@JonLittleIT can you please provide more details. The screenshot shows a success. 

E.g. a full run log, a link to the run. any additional details.

**Comment by JonLittleIT** [comment]
```Run mikepenz/action-junit-report@v3.8.0
  with:
    report_paths: **/dastardly-report.xml
    require_tests: true
    token: ***
    annotate_only: false
    update_check: false
    check_name: JUnit Test Report
    fail_on_failure: false
    require_passed_tests: false
    include_passed: false
    check_retries: false
    transformers: []
    job_summary: true
    detailed_summary: false
    annotate_notice: false
    follow_symlink: false
    job_name: dastardly
📘 Reading input values
📦 Process test results
  Retrieved 1 reports to process.
  Error: Invalid character entity
  Line: [2](https://github.com/Falconcore-ofc/falconcore.io/actions/runs/6306164331/job/17120833518#step:4:2)2[3](https://github.com/Falconcore-ofc/falconcore.io/actions/runs/6306164331/job/17120833518#step:4:3)8
  Column: [7](https://github.com/Falconcore-ofc/falconcore.io/actions/runs/6306164331/job/17120833518#step:4:7)7[9](https://github.com/Falconcore-ofc/falconcore.io/actions/runs/6306164331/job/17120833518#step:4:9)
  Char: ;
```

![image](https://github.com/mikepenz/action-junit-report/assets/22354862/02de82b2-a29e-4568-8bdb-f69792e5e32f)

**Comment by mikepenz** [comment]
Can you please re-build with `Debug` logging enabled? (can perhaps help to further limit the area of the problem)

However, based on the logs I assume your junit report contains invalid characters. 
So the following most likely seems to fail: https://github.com/mikepenz/action-junit-report/blob/main/src/testParser.ts#L153-L154

Given the version in use 3.8.0, which was released in July and not changed since. It also points towards a change in your test report.

**Comment by JonLittleIT** [comment]
<img width="966" alt="image" src="https://github.com/mikepenz/action-junit-report/assets/22354862/d83fe841-fc2f-40e9-9144-737d81edb8e6">

**Comment by mikepenz** [comment]
Based on the last screenshot it seems like the `dastardly-report.xml` has some invalid contents. Is it a file you can share? or which you can look into if it has invalid entries at the defined line and column?

**Comment by mikepenz** [comment]
Based on the last details, this does not look like an issue with the action. Please report back if further questions arrise
